# Site settings
title: Expressly Competitions
email: marc@buyexpressly.com
description: > # this means to ignore newlines until "baseurl:"
 Expressly Competitions
baseurl: ""
url: "https://win.buyexpressly.com"

# Build settings
markdown: kramdown

sass:
    sass_dir: /_scss

collections:
  competitions_local:
    output: true
    permalink: /local/club/competition/:name
  competitions_expressly:
    output: true
    permalink: /expressly-club/competition/:name

defaults:
  -
    scope:
      path: "local/club"
      type: "pages"
    values:
      layout:         "club-layout"
      club_url:       "http://localhost:4000/local/club"
      ga-code:        "UA-102915329-1"
      merchant-uuid:  "m-c2b72f7d-6073-4d91-a05d-55100bc49c2b"
  -
    scope:
      path: "local/club"
      type: "competitions_local"
    values:
      layout:         "club-competition"
      club_url:       "http://localhost:4000/local/club"
      ga-code:        "UA-102915329-1"
      merchant-uuid:  "m-c2b72f7d-6073-4d91-a05d-55100bc49c2b"
  -
    scope:
      path: "expressly-club"
      type: "pages"
    values:
      layout:         "club-layout"
      club-name:      "Expressly Competitions"
      club_url:       "/expressly-club"
      ga-code:        "UA-102915329-1"
      merchant-uuid:  "748f710d-3801-41d2-9235-3c42bf7c6b80"
  -
    scope:
      path: ""
      type: "competitions_expressly"
    values:
      layout:         "club-competition"
      club-name:      "Expressly Competitions"
      club_url:       "/expressly-club"
      ga-code:        "UA-102915329-1"
      merchant-uuid:  "748f710d-3801-41d2-9235-3c42bf7c6b80"
