# Site settings
title: Expressly Competitions
email: marc@buyexpressly.com
description: Expressly Competitions
baseurl: ""
url: "https://win.buyexpressly.com"

# Build settings
markdown: kramdown

sass:
    sass_dir: /_scss

collections:
  club_expressly_campaigns:
    output: true
    permalink: /expressly-club/:path
  club_expressly_pages:
    output: true
    permalink: /expressly-club/:name
  club_nme_campaigns:
    output: true
    permalink: /nme/club/:path
  club_nme_pages:
    output: true
    permalink: /nme/club/:name
  club_trustedreviews_campaigns:
    output: true
    permalink: /trustedreviews/club/:path
  club_trustedreviews_pages:
    output: true
    permalink: /trustedreviews/club/:name

clubs:
  expressly_club: &EXPRESSLY_CLUB
      campaigns:      "club_expressly_campaigns"
      pages:          "club_expressly_pages"
      club-name:      "Expressly Club"
      club_url:       "https://club.buyexpressly.com"
      club_dir:       "/expressly-club"
      club-copyright: "&copy; 2018 Expressly Limited"
      club-logo-nav:  "expressly-white.png"
      company-name:   "Expressly Ltd."
      company-url:    "https://buyexpressly.com"
      company-terms:  "https://buyexpressly.com/terms-and-conditions"
      company-privacy: "https://buyexpressly.com/privacy"
      merchant-uuid:  "748f710d-3801-41d2-9235-3c42bf7c6b80"
      domain-migrations-enabled: false
      ga-code:        "UA-102915329-1"
      ga-domain:      "club.buyexpressly.com"
  nme_club: &NME_CLUB
      campaigns:      "club_nme_campaigns"
      pages:          "club_nme_pages"
      club-name:      "NME AAA"
      club_url:       "https://aaa.nme.com"
      club_dir:       "/nme/club"
      club-copyright: "&copy; 2018 Expressly Limited"
      club-logo-nav:  "nme-aaa-logo.svg"
      company-name:   "Time Inc. UK"
      company-url:    "https://www.timeincuk.com/"
      company-terms:  "https://www.timeincuk.com/terms-and-conditions/"
      company-privacy: "https://www.timeincuk.com/privacy/"
      icon-url:       "https://ksassets.timeincuk.net/wp/uploads/sites/55/2016/10/cropped-nme-site-icon-150x150.jpg"
      merchant-uuid:  "m-63a6456f-6a0f-4ad1-a1ed-4370cb79951d"
      domain-migrations-enabled: true
      ga-code:        "UA-110278937-1"
      ga-domain:      "aaa.nme.com"
      brand-nav-include: nme-nav-bar.html
  trustedreviews_club: &TRUSTEDREVIEWS_CLUB
      campaigns:      "club_trustedreviews_campaigns"
      pages:          "club_trustedreviews_pages"
      club-name:      "TrustedReviews Insider"
      club_url:       "https://trustedreviews.buyexpressly.com"
      club_dir:       "/trustedreviews/club"
      club-copyright: "&copy; 2018 Expressly Limited"
      club-logo-nav:  "trustedreviews-logo.svg"
      company-name:   "Time Inc. UK"
      company-url:    "https://www.timeincuk.com/"
      company-terms:  "https://www.timeincuk.com/terms-and-conditions/"
      company-privacy: "https://www.timeincuk.com/privacy/"
      icon-url:       "http://ksassets.timeincuk.net/wp/uploads/sites/54/2017/07/cropped-trusted-reviews-icon-3-192x192.png"
      merchant-uuid:  "m-1a7b03af-82ba-482f-952c-5e7228bf10d5"
      domain-migrations-enabled: true
      ga-code:        "UA-110278937-2"
      ga-domain:      "trustedreviews.buyexpressly.com"
#      brand-nav-include: nme-nav-bar.html

defaults:
  -
    scope:
      path: "expressly-club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *EXPRESSLY_CLUB
  -
    scope:
      path: ""
      type: "club_expressly_campaigns"
    values:
      layout: "club-competition"
      <<:     *EXPRESSLY_CLUB
  -
    scope:
      path: ""
      type: "club_expressly_pages"
    values:
      <<:     *EXPRESSLY_CLUB
  -
    scope:
      path: "/nme/club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *NME_CLUB
  -
    scope:
      path: ""
      type: "club_nme_campaigns"
    values:
      layout: "club-competition"
      <<:     *NME_CLUB
  -
    scope:
      path: ""
      type: "club_nme_pages"
    values:
      <<:     *NME_CLUB
  -
    scope:
      path: "/trustedreviews/club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *TRUSTEDREVIEWS_CLUB
  -
    scope:
      path: ""
      type: "club_trustedreviews_campaigns"
    values:
      layout: "club-competition"
      <<:     *TRUSTEDREVIEWS_CLUB
  -
    scope:
      path: ""
      type: "club_trustedreviews_pages"
    values:
      <<:     *TRUSTEDREVIEWS_CLUB
