# Site settings
title: Expressly Competitions
email: marc@buyexpressly.com
description: Expressly Competitions
baseurl: ""
url: "https://win.buyexpressly.com"

# Build settings
markdown: kramdown

sass:
    sass_dir: /_scss

collections:
  club_cyclingweekly_campaigns:
    output: true
    permalink: /cyclingweekly/club/:path
  club_cyclingweekly_pages:
    output: true
    permalink: /cyclingweekly/club/:name
  club_expressly_campaigns:
    output: true
    permalink: /expressly-club/:path
  club_expressly_pages:
    output: true
    permalink: /expressly-club/:name
  club_nme_campaigns:
    output: true
    permalink: /nme/club/:path
  club_nme_pages:
    output: true
    permalink: /nme/club/:name
  club_trustedreviews_campaigns:
    output: true
    permalink: /trustedreviews/club/:path
  club_trustedreviews_pages:
    output: true
    permalink: /trustedreviews/club/:name

clubs:
  cyclingweekly_club: &CYCLINGWEEKLY_CLUB
      campaigns:      "club_cyclingweekly_campaigns"
      pages:          "club_cyclingweekly_pages"
      club-name:      "Cycling Weekly Club"
      club_url:       "https://cyclingweekly.buyexpressly.com"
      club_dir:       "/cyclingweekly/club"
#      club-copyright: "&copy; 2018 Expressly Limited"
      club-logo-nav:  "cyclingweekly-logo.png"
      company-name:   "Time Inc. UK"
      company-url:    "http://www.cyclingweekly.com"
      company-terms:  "http://www.timeincuk.com/terms-and-conditions/"
      company-privacy: "http://www.timeincuk.com/privacy/"
      parent-website-name: "Cycling Weekly"
      parent-website-url: "http://www.cyclingweekly.com/"
      icon-url:       "http://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/2/2016/02/cropped-favicon-copy-32x32.jpg"
      merchant-uuid:  "m-17001ac9-9405-4b4f-ada9-fa90426806cc"
      domain-migrations-enabled: false
      ga-code:        "UA-110278937-3"
      ga-domain:      "cyclingweekly.buyexpressly.com"
      brand-nav-include: cyclingweekly-nav-bar.html
      privacy-url:    "http://www.timeincuk.com/privacy/"
      terms-url:      "http://www.timeincuk.com/terms-and-conditions/"
      optin2p-label-override: "Please email me with special offers and news from Cycling Weekly and <a href='https://www.timeincuk.com/brands/' target='_blank'>other iconic brands</a> within <a href='https://www.timeincuk.com/brands/' target='_blank'>the Time Inc. UK Group</a> (such as UNCUT). You can unsubscribe at any time."
      optin2p-update-hide: true
      optin3p-update-hide: true
  expressly_club: &EXPRESSLY_CLUB
      campaigns:      "club_expressly_campaigns"
      pages:          "club_expressly_pages"
      club-name:      "Expressly Club"
      club_url:       "https://club.expressly.io"
      club_dir:       "/expressly-club"
      club-copyright: "&copy; 2018 Expressly Limited"
      club-logo-nav:  "expressly-white.png"
      club-logo-modal:  "expressly-black.png"
      company-name:   "Expressly Ltd."
      company-url:    "https://buyexpressly.com"
      company-terms:  "https://expressly.io/terms-and-conditions"
      company-privacy: "https://expressly.io/privacy"
      parent-website-name: "Expressly"
      parent-website-url: "https://expressly.io/"
      merchant-uuid:  "748f710d-3801-41d2-9235-3c42bf7c6b80"
#      ad_include:     "ads/expressly/list-top-ad.html"
      ad-card-list:     "ads/expressly/card-list-ad-slot.html"
      ad-processing:     "ads/expressly/processing-ad-slot.html"
      ad-thank-you:     "ads/expressly/card-thank-you-ad-slot.html"
      consent-script: "consent/expressly/consent-script.html"
      domain-migrations-enabled: true
      ga-code:        "UA-110278937-4"
      ga-domain:      "club.expressly.io"
      welcome-modal: "extensions/expressly/welcome-modal.html"
      optin2p-create-hide: true
      optin3p-create-hide: true
      optin2p-update-hide: true
      optin3p-update-hide: true
      nav-container-classes: "bg-main"
  nme_club: &NME_CLUB
      campaigns:      "club_nme_campaigns"
      pages:          "club_nme_pages"
      club-name:      "NME AAA"
      club_url:       "https://aaa.nme.com"
      club_dir:       "/nme/club"
#      club-copyright: "&copy; 2018 Expressly Limited"
      club-logo-nav:  "nme-aaa-logo.svg"
      company-name:   "Time Inc. UK"
      company-url:    "https://www.timeincuk.com/"
      company-terms:  "https://www.timeincuk.com/terms-and-conditions/"
      company-privacy: "https://www.timeincuk.com/privacy/"
      parent-website-name: "NME"
      parent-website-url: "http://www.nme.com/"
      icon-url:       "https://ksassets.timeincuk.net/wp/uploads/sites/55/2016/10/cropped-nme-site-icon-150x150.jpg"
      merchant-uuid:  "m-63a6456f-6a0f-4ad1-a1ed-4370cb79951d"
      domain-migrations-enabled: false
      ad-script: "ads/nme/ad-script.html"
      ad-top: "ads/nme/top-ad-slot.html"
#      ad-content: "ads/nme/content-ad-slot.html"
#      ad-body: "ads/nme/body-ad-slot.html"
      ga-code:        "UA-110278937-1"
      ga-domain:      "aaa.nme.com"
      ga-extra-include: extensions/nme/ga.html
      brand-nav-include: nme-nav-bar.html
      privacy-url:    "http://www.timeincuk.com/privacy/"
      terms-url:      "http://www.timeincuk.com/terms-and-conditions/"
      optin2p-label-override: "Please email me with special offers and news from NME and <a href='https://www.timeincuk.com/brands/' target='_blank'>other iconic brands</a> within <a href='https://www.timeincuk.com/brands/' target='_blank'>the Time Inc. UK Group</a> (such as UNCUT). You can unsubscribe at any time."
      optin2p-update-hide: true
      optin3p-update-hide: true
  trustedreviews_club: &TRUSTEDREVIEWS_CLUB
      campaigns:      "club_trustedreviews_campaigns"
      pages:          "club_trustedreviews_pages"
      club-name:      "TrustedReviews Insider"
      club_url:       "https://trustedreviews.buyexpressly.com"
      club_dir:       "/trustedreviews/club"
#      club-copyright: "&copy; 2018 Expressly Limited"
      club-logo-nav:  "trustedreviews-logo.svg"
      company-name:   "Time Inc. UK"
      company-url:    "https://www.timeincuk.com/"
      company-terms:  "https://www.timeincuk.com/terms-and-conditions/"
      company-privacy: "https://www.timeincuk.com/privacy/"
      parent-website-name: "Trusted Reviews"
      parent-website-url: "http://www.trustedreviews.com/"
      icon-url:       "http://ksassets.timeincuk.net/wp/uploads/sites/54/2017/07/cropped-trusted-reviews-icon-3-192x192.png"
      merchant-uuid:  "m-1a7b03af-82ba-482f-952c-5e7228bf10d5"
      domain-migrations-enabled: true
      ga-code:        "UA-110278937-2"
      ga-domain:      "trustedreviews.buyexpressly.com"
      privacy-url:    "http://www.timeincuk.com/privacy/"
      terms-url:      "http://www.timeincuk.com/terms-and-conditions/"
      optin2p-label-override: "Please email me with special offers and news from Trusted Reviews and <a href='https://www.timeincuk.com/brands/' target='_blank'>other iconic brands</a> within <a href='https://www.timeincuk.com/brands/' target='_blank'>the Time Inc. UK Group</a> (such as UNCUT). You can unsubscribe at any time."
      optin2p-update-hide: true
      optin3p-update-hide: true
#      brand-nav-include: nme-nav-bar.html

defaults:
  -
    scope:
      path: "cyclingweekly/club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *CYCLINGWEEKLY_CLUB
  -
    scope:
      path: ""
      type: "club_cyclingweekly_campaigns"
    values:
      layout: "club-competition"
      <<:     *CYCLINGWEEKLY_CLUB
  -
    scope:
      path: ""
      type: "club_cyclingweekly_pages"
    values:
      <<:     *CYCLINGWEEKLY_CLUB
  -
    scope:
      path: "expressly-club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *EXPRESSLY_CLUB
  -
    scope:
      path: ""
      type: "club_expressly_campaigns"
    values:
      layout: "club-competition"
      <<:     *EXPRESSLY_CLUB
  -
    scope:
      path: ""
      type: "club_expressly_pages"
    values:
      <<:     *EXPRESSLY_CLUB
  -
    scope:
      path: "/nme/club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *NME_CLUB
  -
    scope:
      path: ""
      type: "club_nme_campaigns"
    values:
      layout: "club-competition"
      <<:     *NME_CLUB
  -
    scope:
      path: ""
      type: "club_nme_pages"
    values:
      <<:     *NME_CLUB
  -
    scope:
      path: "/trustedreviews/club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *TRUSTEDREVIEWS_CLUB
  -
    scope:
      path: ""
      type: "club_trustedreviews_campaigns"
    values:
      layout: "club-competition"
      <<:     *TRUSTEDREVIEWS_CLUB
  -
    scope:
      path: ""
      type: "club_trustedreviews_pages"
    values:
      <<:     *TRUSTEDREVIEWS_CLUB
