# Site settings
title: Expressly Competitions
email: marc@buyexpressly.com
description: > # this means to ignore newlines until "baseurl:"
 Expressly Competitions
baseurl: ""
url: "https://win.buyexpressly.com"

# Build settings
markdown: kramdown

sass:
    sass_dir: /_scss

collections:
  competitions_local:
    output: true
    permalink: /local/club/competition/:name
  competitions_expressly:
    output: true
    permalink: /expressly-club/competition/:name

clubs:
  local_dev: &LOCAL_DEV
      collection:     "competitions_local"
      club_url:       "http://localhost:4000/local/club"
      club-name:      "Local Club"
      club-copyright: "&copy; 2017 Expressly Limited"
      merchant-uuid:  "m-c2b72f7d-6073-4d91-a05d-55100bc49c2b"
      ga-code:        "UA-102915329-1"
  expressly_club: &EXPRESSLY_CLUB
      collection:     "competitions_expressly"
      club-name:      "Expressly Club"
      club_url:       "/expressly-club"
      club-copyright: "&copy; 2017 Expressly Limited"
      club-logo-nav:  "expressly-white.png"
      merchant-uuid:  "748f710d-3801-41d2-9235-3c42bf7c6b80"
      ga-code:        "UA-102915329-1"

defaults:
  -
    scope:
      path: "local/club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *LOCAL_DEV
  -
    scope:
      path: ""
      type: "competitions_local"
    values:
      layout: "club-competition"
      <<:     *LOCAL_DEV
  -
    scope:
      path: "expressly-club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *EXPRESSLY_CLUB
  -
    scope:
      path: ""
      type: "competitions_expressly"
    values:
      layout: "club-competition"
      <<:     *EXPRESSLY_CLUB
