# Site settings
title: Expressly Competitions
email: marc@buyexpressly.com
description: Expressly Competitions
baseurl: ""
url: "https://win.buyexpressly.com"

# Build settings
markdown: kramdown

sass:
    sass_dir: /_scss

collections:
  competitions_expressly:
    output: true
    permalink: /expressly-club/:path

clubs:
  expressly_club: &EXPRESSLY_CLUB
      collection:     "competitions_expressly"
      club-name:      "Expressly Club"
      club_url:       "/expressly-club"
      club-copyright: "&copy; 2017 Expressly Limited"
      club-logo-nav:  "expressly-white.png"
      merchant-uuid:  "748f710d-3801-41d2-9235-3c42bf7c6b80"
      ga-code:        "UA-102915329-1"

defaults:
  -
    scope:
      path: "expressly-club"
      type: "pages"
    values:
      layout: "club-layout"
      <<:     *EXPRESSLY_CLUB
  -
    scope:
      path: ""
      type: "competitions_expressly"
    values:
      layout: "club-competition"
      <<:     *EXPRESSLY_CLUB
